import os
import sqlite3
import json
from datetime import datetime
from mcp.server.fastmcp import FastMCP
from typing import List

mcp = FastMCP("McpContextManager")

def get_db_connection(workspace_path: str):
    if not workspace_path:
        raise ValueError("workspace_path is required")

    # Force absolute paths
    workspace_path = os.path.abspath(workspace_path)

    db_path = os.path.join(workspace_path, "context.db")

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS checkpoints (
            task_id TEXT PRIMARY KEY,
            description TEXT,
            status TEXT,
            completed_steps TEXT,
            next_steps TEXT,
            active_files TEXT,
            notes TEXT,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    ''')
    conn.commit()
    return conn

def write_markdown_progress(workspace_path, task_id, description, status, completed_steps, next_steps, active_files, notes):
    try:
        md_path = os.path.join(workspace_path, "progress.md")

        # Read existing to see if we append or overwrite. Actually, we should just overwrite with current best truth
        content = f"# Context & Progress Snapshot\n\n"
        content += f"**Active Task ID:** `{task_id}`\n"
        content += f"**Status:** `{status}`\n"
        content += f"**Description:** {description}\n\n"

        content += "## 📁 Active Files\n"
        for f in active_files:
            content += f"- `{f}`\n"
        content += "\n"

        content += "## ✅ Completed Steps\n"
        for s in completed_steps:
            content += f"- [x] {s}\n"
        content += "\n"

        content += "## ⏳ Next Steps\n"
        for s in next_steps:
            content += f"- [ ] {s}\n"
        content += "\n"

        content += "## 📝 Notes & Context\n"
        content += f"{notes}\n\n"

        content += "---\n*This file is automatically generated by Context Manager MCP. Do not edit formatting manually.*"

        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(content)
    except Exception as e:
        print(f"Failed to write progress.md: {e}")

@mcp.tool()
def save_checkpoint(
    workspace_path: str,
    task_id: str,
    description: str,
    status: str,
    completed_steps: List[str],
    next_steps: List[str],
    active_files: List[str],
    notes: str
) -> str:
    """
    Save or update a task checkpoint/context in the workspace's local database.
    Use this to persist the agent's current progress, completed steps, and what needs to be done next.

    Args:
        workspace_path: Absolute path to the current root workspace directory.
        task_id: Unique identifier for the task (e.g., 'auth_impl', 'bug_404').
        description: Brief description of the overall task.
        status: Current status (e.g., 'in_progress', 'blocked', 'completed').
        completed_steps: List of strings detailing completed actions.
        next_steps: List of strings detailing pending actions.
        active_files: List of absolute paths currently being worked on.
        notes: Arbitrary markdown notes, thoughts, or observations.
    """
    try:
        conn = get_db_connection(workspace_path)
        cursor = conn.cursor()

        now = datetime.now().isoformat()

        cursor.execute('''
            INSERT INTO checkpoints (task_id, description, status, completed_steps, next_steps, active_files, notes, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(task_id) DO UPDATE SET
                description=excluded.description,
                status=excluded.status,
                completed_steps=excluded.completed_steps,
                next_steps=excluded.next_steps,
                active_files=excluded.active_files,
                notes=excluded.notes,
                updated_at=excluded.updated_at
        ''', (
            task_id,
            description,
            status,
            json.dumps(completed_steps),
            json.dumps(next_steps),
            json.dumps(active_files),
            notes,
            now
        ))

        conn.commit()
        conn.close()

        # Write human-readable mirror
        write_markdown_progress(workspace_path, task_id, description, status, completed_steps, next_steps, active_files, notes)

        return f"✅ Checkpoint for task '{task_id}' saved successfully in {workspace_path}/context.db\nA progress.md file was also created for human reference."
    except Exception as e:
        return f"❌ Error saving checkpoint: {str(e)}"

@mcp.tool()
def load_checkpoint(workspace_path: str, task_id: str) -> str:
    """
    Load a previously saved task checkpoint from the workspace's local database.
    Use this to recover context if the session was interrupted or context window was cleared.

    Args:
        workspace_path: Absolute path to the current root workspace directory.
        task_id: Unique identifier for the task to load.
    """
    try:
        conn = get_db_connection(workspace_path)
        cursor = conn.cursor()

        cursor.execute("SELECT * FROM checkpoints WHERE task_id = ?", (task_id,))
        row = cursor.fetchone()
        conn.close()

        if not row:
            return f"❌ Checkpoint '{task_id}' not found in database for workspace {workspace_path}."

        result = [
            f"🔄 CHECKPOINT RECOVERED: {row['task_id']}",
            f"Status: {row['status']}",
            f"Last Updated: {row['updated_at']}",
            f"\n--- Description ---\n{row['description']}",
            f"\n--- Active Files ---"
        ]

        try:
            for item in json.loads(row['active_files']):
                result.append(f"- {item}")
        except: pass

        result.append(f"\n--- Completed Steps ---")
        try:
            for item in json.loads(row['completed_steps']):
                result.append(f"- [x] {item}")
        except: pass

        result.append(f"\n--- Next Steps ---")
        try:
            for item in json.loads(row['next_steps']):
                result.append(f"- [ ] {item}")
        except: pass

        result.append(f"\n--- Notes & Context ---\n{row['notes']}")

        return "\n".join(result)
    except Exception as e:
        return f"❌ Error loading checkpoint: {str(e)}"

@mcp.tool()
def list_active_tasks(workspace_path: str) -> str:
    """
    List all active tasks and their status currently saved in the workspace.

    Args:
        workspace_path: Absolute path to the current root workspace directory.
    """
    try:
        conn = get_db_connection(workspace_path)
        cursor = conn.cursor()

        cursor.execute("SELECT task_id, status, updated_at FROM checkpoints ORDER BY updated_at DESC")
        rows = cursor.fetchall()
        conn.close()

        if not rows:
            return "No active tasks found in this workspace's database."

        result = ["📋 ACTIVE TASKS IN WORKSPACE:"]
        for row in rows:
            result.append(f"- **{row['task_id']}** (Status: *{row['status']}*) - Last updated: {row['updated_at']}")

        return "\n".join(result)
    except Exception as e:
        return f"❌ Error listing active tasks: {str(e)}"

if __name__ == "__main__":
    mcp.run(transport='stdio')
